version: '3.4'

services:

  sead.query.api:
    container_name: sead_query_api
    expose:
      - "8090"
    ports:
      - "8090:8089"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:8089
    env_file: conf/.env

  redis.cache:
    container_name: redis_cache
    # environment:
    #   - REDIS_DATA_DIR=/tmp
    volumes:
      - ${REDIS_DATA_DIR:-/tmp}:/data
    expose:
      - "6379/tcp"